version: '3'

volumes:
  database-data:

services:
  backend:
    image: node
    volumes:
      - ./:/app

    ports:
      - 3001:3001

    working_dir: /app/backend
    entrypoint: yarn backend-start

  frontend:
    image: node
    volumes:
      - ./:/app

    ports:
      - 3000:3000

    working_dir: /app/frontend
    entrypoint: yarn frontend-start

  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
